### PR TITLE
Sharing Feature update

### LINKED ISSUE #4: Sharing Component
Create a Sharing Component that displays a modal, allowing the user to save a list in the database, and generate a unique URL to display the saved list

### LINKED ISSUE #7: Add ability to name lists
To compliment #4 , users should be able to name lists, and the name of a list should display when called

### PR DESCRIPTION
**Pull request by villanovachile**
# Sharing Feature Update

This Pull Requests introduces the sharing feature, implemented with the SharingModal component. There are numerous new additional features, tweaks, and enhancements that will be outlined below.

closes #7
closes #4 

## List Sharing

Lists are now defined by two types: `Unranked` and `Ranked`.

### Sharing Modal
image
Sharing Ranked List

### Unranked lists
Unranked lists are lists which have not been ranked by the user and each item in the list all have a score of 0.

### Ranked lists
Ranked lists are lists which have been ranked by the user and each item in the list all have a score based on the outcome of the ranking process.

### List Titles
Every list, Unranked and Ranked has the ability to give a list a title. Titles are not required to begin the ranking process, however, titles are required in order to share both Unranked and Ranked lists.

### List Tags
When sharing Unranked or Ranked lists, the user has the option to add tags, which will help to increase searchability with the forthcoming pages to display user created Unranked and Ranked lists.

### List Author
When sharing Ranked lists, the user who ranked the list has the option to add their name to display who the list was ranked.

### Edit Mode
Introduced in this update is an Edit Mode. New unranked lists are in Edit Mode by default and have the ability to add a title, add items to the list, remove items, edit items, as well as rearrange items via drag and drop. Unranked lists that have been saved to the database and shared, can then be edited in Edit Mode. Making changes in Edit Mode will not allow you to overwrite or save the existing list, but will instead allow you to save as a new list. Changes made to the items or title will be denoted by a * after the title.

### Sharing Lists
Every shared Unranked or Ranked list requires a title, and at least 3 or more items. A URI is then generated (groundwork added in #10 ) and stored in the database with the list items and associated properties.

#### New unranked list:
- Sharing creates new URI with unranked list type

#### New list, ranked without saving/sharing unranked list:
- Sharing creates new URI for unranked list, then creates new URI for ranked list, and associates it with URI of unranked list

#### Shared Unranked list, ranked with no changes to original title or list items: 
- Sharing creates new URI for ranked list, associates original shared unranked list

#### Shared Ranked list, when ranked again, with no changes made to original title or list items:
- Creates new URI for ranked list, associates with original Unranked list

#### Shared unranked list, changes made to title or items, then ranked:
- Creates new URI for Unranked list and associates it with new URI for Ranked list

#### Shared Ranked list, not re-ranked, changes made to title:
- Associates original Unranked URI (preserving original title) and creates new URI for ranked list

#### Shared ranked list, ranked again, no changes made to title:
- Creates new Ranked URI regardless if results are the same, associates original unranked list

## Backend authentication

Netlify serverless deployment already handles CORS configuration. A serverless function was created to generate new token every 10 seconds. The front end could send a request to the backend to retrieve this token. This worked out in local dev environment as the variable remained stored in the local server's memory, however, once in the production environment the function generated a new token regardless if the minimum 10 second interval had not been met.

A less satisfactory approach had to be made in order add another layer of security. A new serverless function `get_token` has been introduced, which will query the database for the presence of an existing token. If the token does not exist, it will create one and return it to the requesting frontend. If the token already exists, the function will check if the token was modified within the last 60 seconds. If it has been less than 60 seconds since the token was last modified, then the token from the database will be returned to the requesting frontend. If it has been more than 60 since since the token was last modified, then a new token will be generated. The `add_list` function was modified to query the database for the existence of the token and compares it against the head authorization. 

Once the app has been converted to a next.js app on a node.js VPS, a more robust means of authentication will be implemented, which will be more performant. 

## Frontend validation
To bring parity to the backend validation introduced in #13 , all user inputs have the following requirements:

#### item
Each item will be stripped of leading and trailing whitespace.  Empty items cannot be entered, and duplicates are prevented. Additionally, the array must be a minimum of 3 items, and no more than 50.

#### title
Must contain at least one alphabetic character and cannot be empty. Leading or trailing whitespace is stripped. Cannot contain more than 100 characters.

#### tags 
A maximum of 6 tags separated by commas. Duplicates are removed and whitespace is stripped from each tag. Each tag can be no less than 3 characters, and no more than 20 characters, with only alphanumeric characters. Tags are optional.

#### name
Optional. Cannot contain more than 30 characters.

## Other enhancements or changes

- Added tooltips to explain functionality that may need clarification
- Added toast style notifications to give an indication when a user's input fails requirements, or when a function fails, such as  failed fetch requests
- Enhancements made to mobile view, adding a collapsible div for buttons so that list view won't take as much space
- Added instructions for new or empty lists
- Results and ResultItem components have been renamed to RankedList and RankedItem respectively.
- General refactoring
- Changes to for more accessibility friendliness

### CODE REVIEW

**Comment by ash1eygrace** [comment]
Tested the following works well: 

- adding items, removing items, and reordering items all work 
- the tooltips work as expected in the tags and name-sharing section
- validation works in the tags and won't allow special chargers like -, _, and spaces.
- ranking a list works great, and I get the correct results. 
- sharing a list generates a list and opens it. 

### Bug: 

I did fine one where the order of the original unranked list is not preserved. Steps to reproduce:

1. Add three items to the list.
2. Reorder them (remember the order)
3. Rank the list 
4. Rerank the list ** 
5. Share the list 
6. Open the list in a new tab and click on See Unranked List. 

#### What I expect: 

I expect the order of the list that I chose to be preserved. 

#### What happens instead: 

The order of the list is displayed in the order that I ranked. 

This only happens when you rerank the list before sharing.

**Review by ash1eygrace — CHANGES_REQUESTED** [review]
Tested the following works well: 

- adding items, removing items, and reordering items all work 
- the tooltips work as expected in the tags and name-sharing section
- validation works in the tags and won't allow special chargers like -, _, and spaces.
- ranking a list works great, and I get the correct results. 
- sharing a list generates a list and opens it. 

### Bug: 

I did fine one where the order of the original unranked list is not preserved. Steps to reproduce:

1. Add three items to the list.
2. Reorder them (remember the order)
3. Rank the list 
4. Rerank the list ** 
5. Share the list 
6. Open the list in a new tab and click on See Unranked List. 

#### What I expect: 

I expect the order of the list that I chose to be preserved. 

#### What happens instead: 

The order of the list is displayed in the order that I ranked. 

This only happens when you rerank the list before sharing.

**Comment by villanovachile** [comment]
> ### Bug:
> I did fine one where the order of the original unranked list is not preserved. Steps to reproduce:

Thanks for testing! Fixed this along with another bug I found where the scores during re-ranking weren't being reset for new unranked lists in the latest commit [ba25f52](https://github.com/villanovachile/truthtally/pull/14/commits/ba25f5280695b618361c7a24aeeb4af834e239c5)

**Review by ash1eygrace — APPROVED** [review]
The previous bug I reported where the unranked list was not preserved after reranking a list has been solved! Works well!

**Pull request merged**
