### PR TITLE
[Add] List Archives

### LINKED ISSUE #5: [New Feature]: Components to display lists
Create a component to display saved public lists, and perhaps sort by popularity (number of views each list has)

### LINKED ISSUE #6: [New Feature]: Components to display results
Create a component to display saved public results. Will need to ensure that the document in MongoDB is associated with a source list so that users can rate the source list to create and share their own results

### PR DESCRIPTION
**Pull request by villanovachile**
### Description

closes #5
closes #6 

This PR finally brings the updates that completes the [Truth Tally - List Sharing project](https://github.com/orgs/villanovachile/projects/1). In order to bring the list archives to fruition, there needed to be a general site layout with traditional header, footer, navigation, etc. The Truth Tally app itself remains largely untouched, and doesn't flow with the site, so that is something that will need to be redesigned to fully integrate it in the site in a pretty way (I will need your input for that @ash1eygrace lol). 

### Additions
- List Archive pages for Ranked and Unranked lists with pagination, searching, and sorting.
- A new API endpoint `get_lists` which handles all requests for list archives from the frontend.
- Updated code for singleton connection to handle `get_lists`
- Contact page with implementation of ReCAPTCHA v3
- All list archives, searches, pagination, and sorting are handled via SSR

### Testing Instructions
When the staging deploy site is live below, be sure to test the following:

Ensure all testing is carried out both on desktop and mobile.

1. Test all functionality in the Truth Tally app itself, creating lists, sharing lists, ranked and unranked, listed and unlisted.
2. Ensure that the Ranked and Unranked archives display lists, and that searching, sorting, and pagination works.
3. Search for the unlisted and listed lists you created and shared display (listed) or do not display (for unlisted lists) on the page archives
4. Test all pages, including static footer pages, and test Contact page
5.  Test OG meta tags by entering a few pages, lists, archive pages at https://www.opengraph.xyz/

### Bugs/Issues/Suggestions in this PR

- [x] Search field on Unranked and Ranked lists pages is not reset when switching between Unranked and Ranked Lists pages. Reported by @villanovachile | fixed with 3d25289c2f00d8656dd549d75feceaafcad0fb45
- [x] Sort selection is not reset when switching between Unranked and Ranked lists pages. Reported by @villanovachile | fixed with 9d6b55e0cbd29819df01936c5ec24875a2af424b
- [x] Stray `;` on Create New List page. Reported by @villanovachile | fixed with adfea1d66751c830e5f5e3a45612a8a18997d104
- [x] Creating a list and sharing a list work fine, but I did notice that the share a list popup modal is cut off when the viewport is under ~700px. Reported by @ash1eygrace | fixed with adfea1d66751c830e5f5e3a45612a8a18997d104
- [x] On the [ranked](https://dev.truthtallyranker.com/lists/ranked) and [unranked](https://dev.truthtallyranker.com/lists/unranked) list pages it would be good for UX if the first options dropdown default was "All" vs. just "Title". Suggested by @ash1eygrace | fixed with 3d25289c2f00d8656dd549d75feceaafcad0fb45
- [x] Add frontend and backend validation/sanitization for contact form, unranked, and ranked lists pages. Reported by @villanovachile | fixed with 59aea222909e5c1f1621f9d07c6e4320521504bb
- [x]  Consistent use of buttons / boxes with rounded corners to match global style. Reported by @drardin | fixed with 3d25289c2f00d8656dd549d75feceaafcad0fb45 & 79fdbc05cba7b9417c6d174eff57afea810ad865

### CODE REVIEW

**Comment by villanovachile** [comment]
To do: When searching for a list on a Ranked List or Unranked List page, then clicking on a Ranked List or Unranked List page (other than the one you're currently viewing), the search field does not reset. This would likely be confusing for users.

Also a stray semicolon at the bottom of the Truth Tally app on the new list page 🙄 (will be found in `/pages/list/index.js` on line 21.

**Comment by ash1eygrace** [comment]
> Test all functionality in the Truth Tally app itself, creating lists, sharing lists, ranked and unranked, listed and unlisted.

Creating a list and sharing a list work fine, but I did notice that the share a list popup modal is cut off when the viewport is under ~700px. 

https://user-images.githubusercontent.com/29527450/233233267-75fb3eed-bc71-43e3-9967-3c8e8ad44dee.mov

**Comment by villanovachile** [comment]
> Creating a list and sharing a list work fine, but I did notice that the share a list popup modal is cut off when the viewport is under ~700px.

I swear CSS is the bane of my existence 🤓

**Comment by ash1eygrace** [comment]
Can we please have dashes in tags <3

image

Optionally allow spaces and automatically add the dash: 

image

**Comment by ash1eygrace** [comment]
On the [ranked](https://dev.truthtallyranker.com/lists/ranked) and [unranked](https://dev.truthtallyranker.com/lists/unranked) list pages it would be good for UX if the first options dropdown default was "All" vs. just "Title"

image

**Comment by villanovachile** [comment]
> Can we please have dashes in tags <3
> Optionally allow spaces and automatically add the dash:

Yes! Can you make a separate issue for this? Won't be included in this PR, but will definitely be in a subsequent one!

**Comment by villanovachile** [comment]
To do: Add frontend and backend validation/sanitization for contact form, unranked, and ranked lists pages 😓

**Comment by drardin** [comment]
I noticed a bug with the redirection from the Fruits list in Popular Unranked Lists. When selecting this list, it redirects to a list titled "BEATLES ALBUMS".

Also, a styling suggestion is a consistent use of buttons / boxes with rounded corners. There's only a couple of examples I can see where this style isn't matched with the global style:

image

image

image

**Comment by villanovachile** [comment]
>I noticed a bug with the redirection from the Fruits list in Popular Unranked Lists. When selecting this list, it redirects to a list titled "BEATLES ALBUMS".

haha, that's actually caused by having Chat GPT randomly generate lists and it accidentally linked an existing list. Another unfortunate consequence of this is incorrectly dated lists, so sorting by newest/oldest might have unintended behavior. Fortunately, this is only on the staging database, and isn't present on the production database. Likely the staging database will be purged at some point.

> Also, a styling suggestion is a consistent use of buttons / boxes with rounded corners. There's only a couple of examples I can see where this style isn't matched with the global style:

Yes! Eventually things will be redesigned and more unified, but that's definitely something worth fixing in the here and now.

**Comment by villanovachile** [comment]
@drardin @ash1eygrace 

Should all be fixed now. If you could give a quick test 🙏

**Review by ash1eygrace — APPROVED** [review]
> Should all be fixed now. If you could give a quick test 🙏

Tested and the popup modal no longer moves up when the viewport is resized. Also, the default filter as "All" makes for easy searching on the Ranked and Unranked pages!

**Pull request merged**
